askme_malyshev/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('hot/', views.HotView.as_view(), name='hot'),
    path('question/<int:id>/', views.QuestionView.as_view(), name='question'),
    path('ask/', views.AskView.as_view(), name='ask'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('tag/<slug:slug>', views.TagView.as_view(), name='tag'),
]

askme_malyshev/askme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
]

askme_malyshev/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

### example ###

# class Genre(models.Model):
#     name = models.CharField(max_length=30)

# class Author(models.Model):
#     name = models.CharField(max_length=30)
#     birth_date = models.DateField(blanck=True, null=True)

# class Book(models.Model):
#     name = models.CharField(max_length=30)
#     genre = models.ManyToManyField(Genre)
#     author = models.ManyToManyField(Author)
#     published_date = models.DateField(blanck=True, null=True)

# class BookInstance(models.Model):
#     book = models.ForeignKey(Book, on_delete=models.PROTECT)
#     # available
#     # taken
#     # repair

#     TAKEN = 't'
#     AVAILABLE = 'a'
#     REPAIR = 'r'

#     STATUCES = [
#         (TAKEN, 'taken'),
#         (AVAILABLE, 'available'),
#         (REPAIR, 'repair'),
#     ]

#     status = models.CharField(max_length=1, choices=STATUCES)

###


TEXT_LENGTH = 500
NAME_LENGTH = 100
PREVIEW_LEN = 10

class UserProfileModel(User):

    picture = models.ImageField(blank=True, null=True)

    def __str__(self):
        return f'User: {self.get_short_name()}'

    class UserProfileModelManager(models.Manager):
        
        def get_smth(self):
            return 0
    
    objects = UserProfileModelManager()

class TagModel(models.Model):
    name = models.TextField(max_length=NAME_LENGTH)

    def __str__(self):
        return f'Tag: {self.name[:PREVIEW_LEN]}'



class QuestionModel(models.Model):
    name = models.TextField(max_length=NAME_LENGTH)
    text = models.TextField(max_length=TEXT_LENGTH)
    
    user_profile = models.ForeignKey(UserProfileModel, on_delete=models.CASCADE)
    tag = models.ManyToManyField(TagModel)

    def __str__(self):
        return f'Question: {self.name[:PREVIEW_LEN]}'

class AnswerModel(models.Model):
    text = models.TextField(max_length=TEXT_LENGTH)
    correct = models.BooleanField(default=False)

    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfileModel, on_delete=models.CASCADE)

    def __str__(self):
        return f'Question: {self.text[:PREVIEW_LEN]}'

class LikeModel(models.Model):

    user_profile = models.ForeignKey(UserProfileModel, on_delete=models.CASCADE)
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE)

    def __str__(self):
        return f'Question: {self.user.get_short_name()}'





TAGS = [
    {
        'title': f'TAG-{i+1}'
    } for i in range(50)
]

ANSWERS = [
    {
        'id': i,
        'text': f'answer-{i}' * ((i * i * i * i) % 200 + 1),
        'likes': (i * i) % 773,
        'is_correct': False
    } for i in range(100)
]

QUESTIONS = [
    {
        'id': i,
        'title': f'question-{i}',
        'text': f'text-{i}' * ((i * i * i * i) % 100 + 1),
        'likes': (i * i) % 773,
        'answer_amount': (i * i * i) % 773,
        'tags': [
            TAGS[i % len(TAGS)],
            TAGS[(i * i) % len(TAGS)],
            TAGS[(i * i * i) % len(TAGS)],
            TAGS[(i * i * i * i) % len(TAGS)]
        ],
        'answers': [
            ANSWERS[(j * j * j + i * i * i + i * j + 4567) % len(ANSWERS)] for j in range(30)
        ],
    } for i in range(100)
]

USERS = [
    {
        'name': f'user-{i+1}'
    } for i in range(25)
]

askme_malyshev/app/views.py
from django.http import Http404
from django.shortcuts import render
from django.views import View
from django.core.paginator import Paginator

from .models import QUESTIONS, TAGS, USERS

OBJECTS_PER_PAGE = 10

# Create your views here.

class IndexView(View):
    template_name = 'index.html'

    def get(self, request):
        questions = QUESTIONS
        paginator = Paginator(questions, OBJECTS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'tags': TAGS,
            'users': USERS[:10],
            'page_obj': page_obj
        }
        return render(request, template_name=self.template_name, context=context)


class HotView(View):
    template_name = 'index.html'

    def get(self, request):
        questions = QUESTIONS.copy()
        questions.sort(key=lambda e: -e['likes'])
        paginator = Paginator(questions, OBJECTS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'tags': TAGS,
            'users': USERS[:10],
            'is_hot': True,
            'page_obj': page_obj
        }
        return render(request, template_name=self.template_name, context=context)


class QuestionView(View):
    template_name = 'question.html'

    def get(self, request, id):

        question = list(filter(lambda e: e['id'] == id, QUESTIONS))
        if not question:
            raise Http404
        question = question[0]

        answers = question['answers']
        paginator = Paginator(answers, OBJECTS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'question': question,
            'page_obj': page_obj,
            'tags': TAGS,
            'users': USERS[:10]
        }
        return render(request, template_name=self.template_name, context=context)


class AskView(View):
    template_name = 'ask.html'

    def get(self, request):
        context = {
            'tags': TAGS,
            'users': USERS[:10]
        }
        return render(request, template_name=self.template_name, context=context)


class LoginView(View):
    template_name = 'login.html'

    def get(self, request):
        context = {
            'tags': TAGS,
            'users': USERS[:10]
        }
        return render(request, template_name=self.template_name, context=context)


class SignupView(View):
    template_name = 'signup.html'

    def get(self, request):
        context = {
            'tags': TAGS,
            'users': USERS[:10]
        }
        return render(request, template_name=self.template_name, context=context)


class SettingsView(View):
    template_name = 'settings.html'

    def get(self, request):
        context = {
            'tags': TAGS,
            'users': USERS[:10]
        }
        return render(request, template_name=self.template_name, context=context)


class TagView(View):
    template_name = 'tag.html'

    def get(self, request, slug):
        tag = list(filter(lambda e: e['title'] == slug, TAGS))
        if not tag:
            raise Http404
        tag = tag[0]

        questions = []
        for q in QUESTIONS:
            for qt in q['tags']:
                if qt['title'] == tag['title']:
                    questions.append(q)
                    break
        
        paginator = Paginator(questions, OBJECTS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'tags': TAGS,
            'users': USERS[:10],
            'tag': tag,
            'page_obj': page_obj
        }
        return render(request, template_name=self.template_name, context=context)

askme_malyshev/templates/ask.html
{% extends 'base.html' %}

{% block main_column %}

    <form action="">
        <div class="my-title">                        
            <div class="md-3">
                <label for="validationServer03" class="form-label">Title</label>
                <input type="text" class="form-control is-invalid" id="validationServer03" aria-describedby="validationServer03Feedback" required>
                <div id="validationServer03Feedback" class="invalid-feedback">
                Please provide a valid title.
                </div>
            </div>

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Text</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="shgbdflnsdfbidsgvf"></textarea>
            </div>

            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Tags</label>
                <input class="form-control" id="exampleFormControlInput1" placeholder="??adiufb iwdfiy uwbafid?">
            </div>

            <button type="button" class="btn btn-primary btn-lg">ASK!</button>
        </div>
    </form>

{% endblock main_column %}

askme_malyshev/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block page_title %}AskMeMalyshev{% endblock page_title %}</title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/my_styles.css' %}">
    </head>
    <body>
        {% include 'includes/header.html' %}

        <main>
            <div class="row">
                <div class="col-8">
                    {% block main_column %}
                    {% endblock main_column %}
                </div>
                <div class="col-4">
                    {% include 'includes/right_column.html' %}
                </div>
        </main>

        {% include 'includes/footer.html' %}
    </body>

</html>

askme_malyshev/templates/includes/answer_card.html
{% load static %}

<div class="answer-card">
    <div class="row">
        <div class="col-3">
            <div class="my-title">
                <img src="{% static "img/default_picture.jpg" %}" class="small-img" alt="your photo">
            </div>

            <div class="my-title">
                likes: {{ answer.likes }} <br>
                <button type="button" class="btn btn-outline-success">Like</button>
                <button type="button" class="btn btn-outline-danger">Dislike</button>
            </div>
        </div>
        <div class="col-9">

            <div class="my-text">
                {{ answer.text }}
            </div>

            <div class="form-check my-title">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                  Correct!
                </label>
            </div>
            
        </div>
    </div>
</div>

askme_malyshev/templates/includes/footer.html
<footer>
    <div class="my-footer">
        <div class="">
            Copyright © 2022 AskMeMalyshev
        </div>
    </div>
</footer>

askme_malyshev/templates/includes/header.html
{% load static %}

<header>
    <div class="my-header">
        <div class="row">
            <div class="col-4 my-header-title">
                <div>
                    <a href="{% url "app:ask" %}" class="nav-link">AskMeMalyshev</a>
                </div>
            </div>
            <div class="col-4">
                <form class="d-flex my-ask-form" role="search">
                    <input class="form-control me-2" type="search" placeholder="Ask" aria-label="Ask">
                    <button class="btn btn-outline-success" type="submit">Ask</button>
                </form>
            </div>
            <div class="col-4">
                <div class="my-small-user-card">
                    <div class="row">
                        <div class="col-4">
                            <img src="{% static "img/default_picture.jpg" %}" class="small-img" alt="photo">
                        </div>

                        <div class="col-8">
                            <div>
                                <h4>Your name</h4>
                            </div>

                            <nav class="nav nav-fill">
                                <a class="nav-link" style="padding-left: 0px; padding-right: 0px;" href="{% url "app:settings" %}">settings</a>
                                <a class="nav-link" style="padding-left: 0px; padding-right: 0px;" href="#">logout</a>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

askme_malyshev/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

askme_malyshev/templates/includes/question_card.html
{% load static %}

<div class="question-card">
    <div class="row">
        <div class="col-3">
            <div class="my-title">
                <img src="{% static "img/default_picture.jpg" %}" class="my-middle-img" alt="your photo">
            </div>

            <div class="my-title">
                likes: {{ question.likes }} <br>
                <button type="button" class="btn btn-outline-success">Like</button>
                <button type="button" class="btn btn-outline-danger">Dislike</button>
            </div>
        </div>
        <div class="col-9">
            <div class="my-title">
                <div class="my-big-text">
                    <a href="{% url "app:question" id=question.id %}" class="nav-link">
                        {{ question.title }}
                    </a>
                </div>
            </div>

            <div class="my-text">
                {{ question.text }}
            </div>

            <div class="my-title">
                Tags:
            
            
                <div class="">
                    {% for tag in question.tags %}
                        <a href="{% url "app:tag" slug=tag.title %}">
                            <button type="button" class="btn btn-outline-primary">{{tag.title}}</button>
                        </a>
                    {% endfor %}
                </div>
            </div>

            <div class="my-title">
                <a href="#">
                    answer ( {{ question.answer_amount }})
                </a>
            </div>
        </div>
    </div>
</div>

askme_malyshev/templates/includes/right_column.html
<div class="my-title my-big-text">
    <a href="#" class="nav-link">Popular tags</a>
</div>

<div class="my-title">

    {% for tag in tags %}

        <a href="{% url "app:tag" slug=tag.title %}">
            <button type="button" class="btn btn-outline-primary">{{tag.title}}</button>
        </a>

    {% endfor %}
     
</div>


<div class="my-title my-big-text">
    <a href="#" class="nav-link">Best members</a>
</div>

<div class="my-title">
    <div class="list-group">

        {% for usr in users %}
            <a href="#" class="list-group-item list-group-item-action">{{usr.name}}</a>
        {% endfor %}

      </div>
</div>

askme_malyshev/templates/index.html
{% extends 'base.html' %}

{% block main_column %}

    <ul class="nav nav-tabs my-title">
        <li class="nav-item">
            <a class="nav-link {% if not is_hot %}active{% endif %} my-big-text" aria-current="page" href="{% url "app:index" %}">New questions</a>
        </li>

        <li class="nav-item">
            <a class="nav-link {% if is_hot %}active{% endif %} my-big-text" href="{% url "app:hot" %}">Hot questions</a>
        </li>
    </ul>

    {% for question in page_obj %}
        {% include 'includes/question_card.html' %}
    {% endfor %}

    {% include 'includes/paginator.html' %}

{% endblock main_column %}

askme_malyshev/templates/login.html
{% extends 'base.html' %}

{% block main_column %}

    <form class="my-title">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control is-invalid" id="exampleInputPassword1" aria-describedby="validationServer05Feedback" required>
            <div id="validationServer05Feedback" class="invalid-feedback">
                Please provide a valid password.
            </div>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">LogIn</button>
        or
        <a href="#">register</a>
    </form>

{% endblock main_column %}

askme_malyshev/templates/question.html
{% extends 'base.html' %}

{% block main_column %}

    {% include 'includes/question_card.html' %}

    {% for answer in page_obj %}

        {% include 'includes/answer_card.html' %}

    {% endfor %}

    {% include 'includes/paginator.html' %}

    <hr>
    <form action="">
        <div class="my-title">                        
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Enter your answer</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="shgbdflnsdfbidsgvf"></textarea>
            </div>

            <button type="button" class="btn btn-primary btn-lg">Answer!</button>
        </div>
    </form>

{% endblock main_column %}

askme_malyshev/templates/settings.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>AskMeMalyshev</title>

        <link rel="stylesheet" href="../static/css/bootstrap.css">
        <link rel="stylesheet" href="../static/css/my_styles.css">
    </head>

    <body>
        <header>
            <div class="my-header">
                <div class="row">



                    <div class="col-4 my-header-title">
                        <div>
                            <a href="#" class="nav-link">AskMeMalyshev</a>
                        </div>
                    </div>




                    <div class="col-4">
                        <form class="d-flex my-ask-form" role="search">
                            <input class="form-control me-2" type="search" placeholder="Ask" aria-label="Ask">
                            <button class="btn btn-outline-success" type="submit">Ask</button>
                        </form>
                    </div>



                    <div class="col-4">
                        


                        <div class="my-small-user-card">
                            <div class="row">
                                <div class="col-4">
                                    <img src="../static/img/default_picture.jpg" class="small-img" alt="photo">
                                </div>
    
                                <div class="col-8">
                                    <div>
                                        <h4>Your name</h4>
                                    </div>

                                    <nav class="nav nav-fill">
                                        <a class="nav-link" style="padding-left: 0px; padding-right: 0px;" href="#">settings</a>
                                        <a class="nav-link" style="padding-left: 0px; padding-right: 0px;" href="#">logout</a>
                                    </nav>
                                </div>
                            </div>
                        </div>
                        




                    </div>
                </div>
            </div>
        </header>

        <main>
            <div class="row">
                <div class="col-8">
                    






                    
                    <form action="" class="my-title">
                        <div class="my-title my-big-text">
                            Settings:
                            YourName
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Login</label>
                            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="pudabs">
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">NickName</label>
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="gwdgdlwddj">
                        </div>

                        
                        <div>
                            <label for="image_uploads">Choose images to upload (PNG, JPG)</label>
                            <input type="file" id="image_uploads" name="image_uploads" accept=".jpg, .jpeg, .png" multiple>
                        </div>

                        <div class="preview">
                            <div class="my-title">
                                <img src="../static/img/default_picture.jpg" class="my-middle-img" alt="your photo">
                            </div>
                        </div>
                          

                        <button type="button" class="btn btn-primary btn-lg">Save!</button>

                    </form>




                    


                    

                </div>

                <div class="col-4">
                    <div class="my-title my-big-text">
                        <a href="#" class="nav-link">Popular tags</a>
                    </div>
                    
                    <div class="my-title">
                        <button type="button" class="btn btn-outline-primary">Primary</button>
                        <button type="button" class="btn btn-outline-secondary">Secondary</button>
                        <button type="button" class="btn btn-outline-success">Success</button>
                        <button type="button" class="btn btn-outline-danger">Danger</button>
                        <button type="button" class="btn btn-outline-warning">Warning</button>
                        <button type="button" class="btn btn-outline-info">Info</button>
                        <button type="button" class="btn btn-outline-dark">Dark</button>  
                        <button type="button" class="btn btn-outline-primary">Primary</button>
                        <button type="button" class="btn btn-outline-secondary">Secondary</button>
                        <button type="button" class="btn btn-outline-success">Success</button>
                        <button type="button" class="btn btn-outline-danger">Danger</button>
                        <button type="button" class="btn btn-outline-warning">Warning</button>
                        <button type="button" class="btn btn-outline-info">Info</button>
                        <button type="button" class="btn btn-outline-dark">Dark</button>  
                        <button type="button" class="btn btn-outline-primary">Primary</button>
                        <button type="button" class="btn btn-outline-secondary">Secondary</button>
                        <button type="button" class="btn btn-outline-success">Success</button>
                        <button type="button" class="btn btn-outline-danger">Danger</button>
                        <button type="button" class="btn btn-outline-warning">Warning</button>
                        <button type="button" class="btn btn-outline-info">Info</button>
                        <button type="button" class="btn btn-outline-dark">Dark</button> 
                        <button type="button" class="btn btn-outline-primary">Primary</button>
                        <button type="button" class="btn btn-outline-secondary">Secondary</button>
                        <button type="button" class="btn btn-outline-success">Success</button>
                        <button type="button" class="btn btn-outline-danger">Danger</button>
                        <button type="button" class="btn btn-outline-warning">Warning</button>
                        <button type="button" class="btn btn-outline-info">Info</button>
                        <button type="button" class="btn btn-outline-dark">Dark</button>  
                        <button type="button" class="btn btn-outline-primary">Primary</button>
                        <button type="button" class="btn btn-outline-secondary">Secondary</button>
                        <button type="button" class="btn btn-outline-success">Success</button>
                        <button type="button" class="btn btn-outline-danger">Danger</button>
                        <button type="button" class="btn btn-outline-warning">Warning</button>
                        <button type="button" class="btn btn-outline-info">Info</button>
                        <button type="button" class="btn btn-outline-dark">Dark</button>  
                        <button type="button" class="btn btn-outline-primary">Primary</button>
                        <button type="button" class="btn btn-outline-secondary">Secondary</button>
                        <button type="button" class="btn btn-outline-success">Success</button>
                        <button type="button" class="btn btn-outline-danger">Danger</button>
                        <button type="button" class="btn btn-outline-warning">Warning</button>
                        <button type="button" class="btn btn-outline-info">Info</button>
                        <button type="button" class="btn btn-outline-dark">Dark</button>    
                    </div>
                    
                    
                    <div class="my-title my-big-text">
                        <a href="#" class="nav-link">Best members</a>
                    </div>

                    <div class="my-title">
                        <div class="list-group">
                            <a href="#" class="list-group-item list-group-item-action">m</a>
                          
                            <a href="#" class="list-group-item list-group-item-action list-group-item-primary">a</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-secondary">b</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-success">c</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-danger">d</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-warning">e</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-info">e</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-light">f</a>
                            <a href="#" class="list-group-item list-group-item-action list-group-item-dark">g</a>
                          </div>
                    </div>
                </div>
            </div>

        </main>

        <footer>
            <div class="my-footer">
                <div class="">
                    Copyright © 2022 AskMeMalyshev
                </div>
            </div>
        </footer>
        
    </body>
</html>

askme_malyshev/templates/signup.html
{% extends 'base.html' %}

{% block main_column %}

    <form class="my-title">
                            
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Login</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="pudabs">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">NickName</label>
            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="gwdgdlwddj">
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1">
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Repeat password</label>
            <input type="password" class="form-control" id="exampleInputPassword1">
        </div>

        
        <div>
            <label for="image_uploads">Choose images to upload (PNG, JPG)</label>
            <input type="file" id="image_uploads" name="image_uploads" accept=".jpg, .jpeg, .png" multiple>
        </div>

        <div class="preview">
            <div class="my-title">
                <img src="../static/img/default_picture.jpg" class="my-middle-img" alt="your photo">
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Register</button>

    </form>

{% endblock main_column %}

askme_malyshev/templates/tag.html
{% extends 'base.html' %}

{% block main_column %}

    <div class="my-title my-big-text">
        Tag:
        <a href="{% url "app:tag" slug=tag.title %}">
            <button type="button" class="btn btn-outline-primary">{{tag.title}}</button>
        </a>
    </div>

    {% for question in page_obj %}
        {% include 'includes/question_card.html' %}
    {% endfor %}

    {% include 'includes/paginator.html' %}

{% endblock main_column %}